on: push

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            console.log('github.workspace: ${{ github.workspace }}')

            const writeStream = fs.createWriteStream('${{ github.workspace }}/src/test.ts')
            writeStream.write('export default <string[]>[]')
            writeStream.end()
            
            fs.readFile('${{ github.workspace }}/src/test.ts', (err, data) => {
              if (err) {
                  throw err;
              }
              console.log('data here', data)
            });